# ============================================================
# APPLICATION
# ============================================================
spring.application.name=notification-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
server.port=2001
server.servlet.context-path=/api

# ============================================================
# MAILJET CONFIG
# ============================================================
mailjet.api-key=b242038d9567fe0801cc5495b217aea1
mailjet.secret-key=96320060cbcd7f1ce30a59ebc4a551f1
mailjet.sender-email=blink@akrem.dev
mailjet.sender-name=ESM Platform

# ============================================================
# SWAGGER
# ============================================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ============================================================
# LOGGING
# ============================================================
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n